{% set name = "inmoose" %}
{% set version = "0.7.2" %}
{% set sha256 = "e7e16d0d20335476f66a24158f26cbadac4f1c8244684441f5b2451c1ae3c8b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/epigenelabs/inmoose/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  
build:
  noarch: python
  number: 0
  run_exports:
  - {{ pin_subpackage(name, max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"
  entry_points:
    - inmoose = inmoose.__master__:root_command

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - seaborn
    - matplotlib
    - biopython
    - tqdm
    - pysam
    - networkx
    - h5py
    - psutil
    - lmfit
    - click
    - scanpy
    - anndata
    - scikit-learn


test:
  imports:
    - inmoose
    - inmoose.pycombat
    - inmoose.consensus_clustering.consensus_clustering

  commands:
    - inmoose --help
    - inmoose --version

about:
  home: https://github.com/epigenelabs/inmoose/tree/master
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: 'InMoose is the Integrated Multi Omic Open Source Environment. It is a collection of tools for the analysis of omic data.'

extra:
  container:
    # click requires a unicode locale when used with Python 3
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: true  # [py3k]